export default [
  {
    title: "Basic",
    price: "$20.00",
    hint: "1 press release",
    description: "Guaranteed News Distribution with Media Coverage",
    features: [
      { text: "Google Inclusion", icon: "/packages/google.png", included: true },
      { text: "150 Guaranteed Placements", included: true },
      { text: "Google News Inclusion", icon: "/packages/googlenews.png", included: false },
      { text: "Yahoo Inclusion", icon: "/packages/yahoo.png", included: true },
      { text: "Bing Inclusion", icon: "/packages/bing.png", included: true },
      { text: "Financial Feeds", included: true },
      { text: "Online Newspaper", included: true },
      { text: "Market Watch", icon: "/packages/marketwatch.png", included: false },
      { text: "Digital Journal", icon: "/packages/digitaljournal.png", included: false },
      { text: "Fox Media Outlets", icon: "/packages/fox.png", included: false },
      { text: "NBC Media Outlets", icon: "/packages/nbc.jpg", included: false },
      { text: "CBS Media Outlets", icon: "/packages/cbs.jpg", included: false },
      { text: "Anchor Text Links within PR-10", included: true },
      { text: "800 word count limit", included: true },
      { text: "Images-5", included: true },
    ],
    demo: "https://dashboard.kingnewswire.com/report/new-free-online-heic-to-jpg-converter-simplifies-iphone-photo-sharing",
    options: [
      "1 press release for $20.00",
      "5 press releases for $90.00",
      "10 press releases for $130.00",
      "20 press releases for $180.00",
      "100 press releases for $750.00",
    ],
  },
  {
    title: "Standard",
    price: "$30.00",
    hint: "1 press release",
    description: "Guaranteed News Distribution with Media Coverage",
    features: [
      { text: "350 Guaranteed Placements", included: true },
      { text: "Google News Inclusion", icon: "/packages/googlenews.png", included: true },
      { text: "Google Inclusion", icon: "/packages/google.png", included: true },
      { text: "Yahoo Inclusion", icon: "/packages/yahoo.png", included: true },
      { text: "Bing Inclusion", icon: "/packages/bing.png", included: true },
      { text: "Financial Feeds", included: true },
      { text: "Online Newspaper", included: true },
    ],
    demo: "#",
    options: ["1 press release for $30.00"],
  },
  {
    title: "Premium",
    price: "$70.00",
    hint: "1 press release",
    description: "Guaranteed News Distribution with Media Coverage",
    features: [
      { text: "450 Guaranteed Placements", included: true },
      { text: "Digital Journal", icon: "/packages/digitaljournal.png", included: true },
      { text: "Street Insider", icon: "/packages/streetinsider.png", included: true },
      { text: "Fox Media Outlets", icon: "/packages/fox.png", included: true },
      { text: "TV Station Media Sites", included: true },
      { text: "Google Inclusion", icon: "/packages/google.png", included: true },
    ],
    demo: "#",
    options: ["1 press release for $70.00"],
  },
];